FROM ubuntu

WORKDIR /app

COPY . .

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install default-jdk -y
RUN apt-get install nodejs -y
RUN apt-get install maven -y
RUN apt-get clean
RUN wget https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.13.8.linux-amd64.tar.gz
RUN export PATH=$PATH:/usr/local/go/bin
RUN rm -rf go1.13.8.linux-amd64.tar.gz
RUN npm i

EXPOSE 8080

CMD [ "node","app.js" ]