FROM ubuntu

WORKDIR /app

RUN apt-get update
RUN apt-get install wget -y
RUN apt-get install curl -y
RUN apt-get install git -y
RUN apt-get install default-jdk -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install nodejs -y
RUN apt-get install maven -y
RUN apt-get clean
RUN wget https://dl.google.com/go/go1.13.8.linux-386.tar.gz
RUN tar -C /usr/local -xzf go1.13.8.linux-386.tar.gz
RUN echo "export PATH=$PATH:/usr/local/go/bin" > /root/.bash_aliases
RUN rm -rf go1.13.8.linux-386.tar.gz